file1=open('Assignment 4/output.txt', 'w')
input1=input("Enter text to write to the file:")
file1.write(input1)
print("Data successfully written to output.txt.")
file1.close()
file2=open('Assignment 4/output.txt', 'a')
input2=input("Enter additional text to append :")
file2.write('\n'+input2)
print("Data successfully appended to output.txt.")
file2.close()

file3=open('Assignment 4/output.txt', 'r')
print("Contents of output.txt:")
print(file3.read())
file3.close()